# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8267ab5c149400450a61a2de68be4d498bdeb469c75ca7d84a29904f01f3276e469f5adff140ea8864b3f024ba7ea85bfe7b022574542580817b12052d8f5440

test:
  secret_key_base: 530c94e517cb09272c4875d321135a9aaa153cd18a1bdfa14cbe917600536e3bf492c23f971cfccbc24f2e075b7dd21ef5729c0ed092d7272ff09d32ad056eb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
